Update sakai_21_mysql_conversion.sql
sakaiproject/sakai-reference pull request #105
Opened 2020-12-12 15:30 UTC by csev

Need some help with the Oracle bits @bjones86  - Thanks in advance

2020-12-14 13:19 UTC, bjones86 commented
Oracle equivalent:

```
ALTER TABLE lti_tools ADD pl_coursenav NUMBER(1,0) DEFAULT 0;
```

2020-12-14 13:20 UTC, bjones86 requested changes

2020-12-14 13:20 UTC, bjones86 commented on docs/conversion/sakai_21_mysql_conversion.sql
> +ALTER TABLE lti_tools ADD     pl_coursenav TINYINT DEFAULT '0'
The default should be `0`, not `'0'` (number vs. string):

```suggestion
ALTER TABLE lti_tools ADD pl_coursenav TINYINT DEFAULT 0;
```

2021-03-01 16:22 UTC, bjones86 commented
Please remember to update the commit message with the SAK # when merging this.

2021-03-17 21:28 UTC, ern commented
Closing, as this is already incorporated

2021-03-17 21:28 UTC, closed without merging