S2U-21 5.1.1.10 Canceled questions and score re-calculation
sakaiproject/sakai-reference pull request #191
Opened 2023-03-08 17:45 UTC by stetsche

Conversion scripts for:

- https://sakaiproject.atlassian.net/browse/S2U-14
- https://github.com/sakaiproject/sakai/pull/11328

2023-03-10 07:39 UTC, jesusmmp commented
Title should be S2U-14.
@mpellicer Please add uni-digital label. I haven't got permission on this repo. Thanks!

2023-03-13 08:03 UTC, stetsche commented
Thanks! Commit message was wrong too :)

2023-03-13 11:21 UTC, mpellicer commented on docs/conversion/s2u_features/S2U-14-mysql.sql
> +ALTER TABLE SAM_PUBLISHEDITEM_T ADD CANCELLED INT(11) DEFAULT 0 NOT NULL;
Should we use a TINYINT for this using only 1 byte? We cover probably all the cases

2023-03-13 11:23 UTC, mpellicer commented on docs/conversion/s2u_features/S2U-14-oracle.sql
> +ALTER TABLE SAM_PUBLISHEDITEM_T ADD CANCELLED NUMBER(10,0) DEFAULT 0 NOT NULL;
Seems too much for me to store something smaller than 100, do you know if number(2,0) is enough?

2023-03-13 11:23 UTC, mpellicer requested changes
Discussion around precission.

2023-03-13 11:23 UTC, mpellicer commented
> Title should be S2U-14. @mpellicer Please add uni-digital label. I haven't got permission on this repo. Thanks!

Thanks!

2023-03-13 12:22 UTC, mpellicer commented on docs/conversion/s2u_features/S2U-14-mysql.sql
> +ALTER TABLE SAM_PUBLISHEDITEM_T ADD CANCELLED INT(11) DEFAULT 0 NOT NULL;
I think the name should be 'CANCELLATION', could you confirm?

2023-03-13 12:27 UTC, mpellicer approved these changes
Tested both scripts in MySQL and Oracle, good job so far!

2023-03-13 12:27 UTC, merged