SAK-47843 Add new conversation split topic permissions
sakaiproject/sakai-reference pull request #225
Opened 2023-10-28 09:51 UTC by adrianfish

https://sakaiproject.atlassian.net/browse/SAK-47843

2023-10-28 16:28 UTC, csev commented
Don't you also have to fix all the sites created since Sakai 23?

2023-10-28 17:06 UTC, adrianfish commented
@csev Yes, but I think you'd usually do that with a script. At least we did at longsight.

2024-04-12 15:32 UTC, ern approved these changes

2024-10-30 09:59 UTC, jesusmmp commented
Please, move this to sakai 25 scripts. Thanks.

2024-12-19 09:07 UTC, jesusmmp requested changes
Pls, move it to the correct files. Thanks!

2025-01-03 09:36 UTC, closed without merging