SAK-44636 - Add pl_lessonselection column
sakaiproject/sakai-reference pull request #98
Opened 2020-11-14 20:27 UTC by csev

Set default to 1 since this value did not exist but was assumed to be 1 in the service pre-21.

Please help me with the oracle variant @bjones86 or @davidpbauer - thansk in advance

2020-11-16 14:39 UTC, bjones86 commented
Oracle equivalent:

```
ALTER TABLE lti_tools ADD pl_lessonsselection NUMBER(1) DEFAULT 0;
UPDATE lti_tools SET pl_pl_lessonsselection = 1;
```

It's pretty much the exact same in this case, just a different datatype.

2020-11-16 14:39 UTC, bjones86 commented on docs/conversion/sakai_21_mysql_conversion.sql
> +ALTER TABLE lti_tools ADD pl_lessonsselection TINYINT DEFAULT '0';
I believe the default should be `0`, not `'0'` (number, not a string).

2020-11-17 14:18 UTC, ern requested changes
These need to be added to the 20 scripts vs 21 scripts.

2020-11-17 14:43 UTC, ern approved these changes

2020-11-17 14:43 UTC, merged